### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by Zaxcoding** [bewest/decoding-dexcom#3]
Hello,

I'm not sure if you have any interest in this project any more, but my girlfriend recently got a Dexcom G4 and after discovering their software is incompatible with OSX, I quickly found this repo as a solution. I'm going to be doing some development to try to properly graph the data and make it more usable for those unfamiliar with the command line, but I'm extremely grateful for what you've accomplished so far. Thank you.

I'd like to suggest you add a simple 'setup' section to your readme. Something like:
# Setup

These scripts rely on dexcom_reader: https://github.com/compbrain/dexcom_reader. 
To install:

``` bash
$ git clone https://github.com/bewest/decoding-dexcom.git
$ cd decoding-dexcom/dexcom_reader
$ git clone https://github.com/compbrain/dexcom_reader.git
```

then to test that everything worked, try

``` bash
$ python dxcom-scan
```

**Comment by bewest** [comment]
Many thanks, I've updated the README with your suggestion.

Constructive criticism is always welcome!  Patches/suggestions are always welcome.
I'm very interested in this still; recently I've been focusing on https://github.com/bewest/decoding-carelink (does she use a pump?).

@Zaxcoding, you may want to meet @alexandre-normand, who has java and objective-c implementations for dexcom!
