### ISSUE TITLE
dxcom-records-cgm: Readings are 2hr 20min delayed

### ISSUE THREAD

**Issue by hanneshapke** [bewest/decoding-dexcom#5]
When I am reading my dexcom data with

```
python dxcom-records-cgm
```

I am only getting all readings until 2 hours plus some minutes ago.
When I run

```
python dxcom-records-sensor
```

I am seeing a few more records. Why is that the case?

**Comment by compbrain** [comment]
I think https://github.com/compbrain/dexcom_reader/commit/471e3c833ee7294c0911304cec06e8111df38ace fixes that.

**Comment by hanneshapke** [comment]
Thank you for the fix. The fix solved the problem. Thank you!
