### ISSUE TITLE
Option to read only last page

### ISSUE THREAD

**Issue by scottleibrand** [bewest/decoding-dexcom#7]
I'd like to run dxcom-records-cgm and only get back the last page worth of CGM readings, to cut down on the time and power consumed checking the CGM.  Can we add a flag to dxcom-records-cgm, or another command to do that?

Really I only need the last two CGM readings, but I don't think there's anything to be gained by limiting the output below a single page.

**Comment by mgranberry** [comment]
```
from dexcom_reader import readdata
dd = readdata.Dexcom.FindDevice()
dr = readdata.Dexcom(dd)
start, end = dr.ReadDatabasePageRange('EGV_DATA')
records = []
records.extend(dr.ReadDatabasePage('EGV_DATA', end))
records[-2:]
```

Of course this will blow up if there is only one record available on the current page.

**Comment by scottleibrand** [comment]
Awesome, thanks!  That's exactly what I needed.

-Scott

On Tue, Apr 7, 2015 at 9:40 AM, Matthias Granberry <notifications@github.com
